# Generated by Django 5.1.7 on 2025-05-12 05:13

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HerdSire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('semen_type', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('regular', 'Regular')], default='regular', max_length=10)),
                ('profile_link', models.URLField(blank=True, null=True)),
                ('cleanup_method', models.CharField(blank=True, choices=[('natural', 'Natural'), ('ai', 'Artificial Insemination')], max_length=10, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='LeasedBull',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ear_tag', models.CharField(max_length=20)),
                ('breed', models.CharField(blank=True, max_length=50)),
                ('dob', models.DateField(blank=True, null=True)),
                ('lease_start', models.DateField()),
                ('lease_end', models.DateField(blank=True, null=True)),
                ('owner_name', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cattle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregnancy_status', models.CharField(blank=True, choices=[('open', 'Open'), ('bred', 'Bred')], default='', help_text='Current pregnancy status', max_length=10, null=True)),
                ('ear_tag', models.CharField(max_length=20, unique=True)),
                ('registration_number', models.CharField(blank=True, max_length=100, null=True)),
                ('breed', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6)),
                ('breeding_method', models.CharField(choices=[('natural', 'Natural'), ('ai', 'Artificial Insemination')], default='', help_text='How the animal was bred', max_length=10)),
                ('sire_type', models.CharField(blank=True, choices=[('owned', 'Owned'), ('donor', 'Donor'), ('leased', 'Leased')], max_length=10, null=True)),
                ('status', models.CharField(choices=[('alive', 'Alive'), ('sold', 'Sold'), ('deceased', 'Deceased')], default='alive', max_length=10)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sale_date', models.DateField(blank=True, null=True)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('purchased_from', models.CharField(blank=True, max_length=255, null=True)),
                ('sold_to', models.CharField(blank=True, max_length=255, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='cattle_photos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])])),
                ('animal_type', models.CharField(choices=[('heifer', 'Heifer'), ('cow', 'Cow'), ('bull', 'Bull'), ('steer', 'Steer')], default='', max_length=10)),
                ('dam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dam_of', to='cattle_tracker_app.cattle')),
                ('sire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cattle_tracker_app.cattle')),
                ('herd_sire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cattle_tracker_app.herdsire')),
            ],
        ),
        migrations.CreateModel(
            name='CalvingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField()),
                ('birth_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('health_notes', models.TextField(blank=True, null=True)),
                ('calf', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='birth_record', to='cattle_tracker_app.cattle')),
                ('dam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calves_birthed', to='cattle_tracker_app.cattle')),
                ('sire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calves_sired', to='cattle_tracker_app.cattle')),
            ],
        ),
        migrations.CreateModel(
            name='BreedingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breeding_date', models.DateField(default=django.utils.timezone.now)),
                ('pregnancy_confirmation_date', models.DateField(blank=True, null=True)),
                ('expected_calving_date', models.DateField(blank=True, null=True)),
                ('calving_outcome', models.CharField(blank=True, choices=[('successful', 'Successful'), ('miscarriage', 'Miscarriage'), ('stillborn', 'Stillborn')], max_length=20, null=True)),
                ('bull', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offspring_records', to='cattle_tracker_app.cattle')),
                ('cow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breeding_records', to='cattle_tracker_app.cattle')),
                ('offspring', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='born_from', to='cattle_tracker_app.cattle')),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('pregnancy_check', 'Pregnancy Confirmation Reminder'), ('calving_reminder', 'Upcoming Calving Reminder'), ('missed_pregnancy', 'Missed Pregnancy Alert'), ('failed_pregnancy', 'Failed Pregnancy Alert')], max_length=20)),
                ('message', models.TextField()),
                ('alert_date', models.DateTimeField()),
                ('resolved', models.BooleanField(default=False)),
                ('cattle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='cattle_tracker_app.cattle')),
            ],
        ),
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateField(auto_now_add=True)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('cattle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='cattle_tracker_app.cattle')),
            ],
        ),
        migrations.CreateModel(
            name='BreedingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breeding_date', models.DateField()),
                ('method', models.CharField(choices=[('natural', 'Natural Breeding'), ('ai', 'Artificial Insemination')], max_length=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_leased', models.BooleanField(default=False)),
                ('cleanup_method', models.CharField(blank=True, choices=[('ai', 'Artificial Insemination'), ('natural', 'Natural Breeding')], help_text='How the cow was cleaned up after initial breeding', max_length=10, null=True)),
                ('bull', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sired_offspring', to='cattle_tracker_app.cattle')),
                ('cleanup_sire', models.ForeignKey(blank=True, help_text='Used for natural breeding cleanup', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cleanup_breedings', to='cattle_tracker_app.cattle')),
                ('cow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breeding_attempts', to='cattle_tracker_app.cattle')),
                ('cleanup_herd_sire', models.ForeignKey(blank=True, help_text='AI sire used for cleanup', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cleanup_breeding_usages', to='cattle_tracker_app.herdsire')),
                ('herd_sire', models.ForeignKey(blank=True, help_text='AI sire used for this breeding', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='breeding_usages', to='cattle_tracker_app.herdsire')),
            ],
        ),
        migrations.CreateModel(
            name='IllnessRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('illness_name', models.CharField(max_length=100)),
                ('diagnosis_date', models.DateField()),
                ('treatment', models.TextField(blank=True, null=True)),
                ('recovery_status', models.CharField(choices=[('recovering', 'Recovering'), ('recovered', 'Recovered'), ('chronic', 'Chronic'), ('deceased', 'Deceased')], default='recovering', max_length=10)),
                ('cattle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='illness_records', to='cattle_tracker_app.cattle')),
            ],
        ),
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('filename', models.CharField(max_length=255)),
                ('record_type', models.CharField(max_length=50)),
                ('success_count', models.PositiveIntegerField(default=0)),
                ('failure_count', models.PositiveIntegerField(default=0)),
                ('error_log', models.TextField(blank=True)),
                ('imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cattle',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cattle_tracker_app.owner'),
        ),
        migrations.CreateModel(
            name='OwnerUserAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('manager', 'Manager'), ('vet', 'Veterinarian'), ('farmhand', 'Farmhand')], max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cattle_tracker_app.owner')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pasture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location_description', models.CharField(blank=True, max_length=255)),
                ('size_acres', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('boundary', models.JSONField(blank=True, null=True)),
                ('total_size_acres', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('number_of_paddocks', models.PositiveIntegerField(blank=True, null=True)),
                ('avg_paddock_size_acres', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('geometry', models.JSONField(blank=True, null=True)),
                ('acres', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('water_source_type', models.CharField(blank=True, choices=[('pond', 'Pond'), ('well', 'Well'), ('creek', 'Creek'), ('trough', 'Trough'), ('other', 'Other')], max_length=100)),
                ('water_quantity_gallons', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
       
        migrations.AddField(
            model_name='cattle',
            name='pasture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cattle', to='cattle_tracker_app.pasture'),
        ),
        migrations.CreateModel(
            name='PregnancyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregnancy_confirmed', models.BooleanField(default=False)),
                ('expected_due_date', models.DateField(blank=True, null=True)),
                ('pregnancy_status', models.CharField(choices=[('pregnant', 'Pregnant'), ('aborted', 'Aborted'), ('stillbirth', 'Stillbirth'), ('successful', 'Successful')], default='ongoing', max_length=12)),
                ('notes', models.TextField(blank=True, null=True)),
                ('breeding_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pregnancy', to='cattle_tracker_app.breedingrecord')),
                ('cow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pregnancies', to='cattle_tracker_app.cattle')),
            ],
        ),
        migrations.CreateModel(
            name='TurnoutGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Optional name for this group (e.g., Spring Breeding 2025)', max_length=100)),
                ('turn_in_date', models.DateField()),
                ('turn_out_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('bulls', models.ManyToManyField(help_text='Bulls used for natural breeding', related_name='turnout_groups_as_bull', to='cattle_tracker_app.cattle')),
                ('cows', models.ManyToManyField(help_text='Cows/Heifers turned out for breeding', related_name='turnout_groups_as_cow', to='cattle_tracker_app.cattle')),
                ('owners', models.ManyToManyField(help_text='Owners involved in this group (optional)', to='cattle_tracker_app.owner')),
            ],
            options={
                'verbose_name': 'Turnout Group',
                'verbose_name_plural': 'Turnout Groups',
            },
        ),
        migrations.CreateModel(
            name='VaccinationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_name', models.CharField(max_length=100)),
                ('date_given', models.DateField()),
                ('next_due', models.DateField(blank=True, null=True)),
                ('cattle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccination_records', to='cattle_tracker_app.cattle')),
            ],
        ),
        migrations.CreateModel(
            name='WeightLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('notes', models.TextField(blank=True, null=True)),
                ('cattle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight_logs', to='cattle_tracker_app.cattle')),
            ],
        ),
    ]
