# Generated by Django 5.1.7 on 2025-05-12 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cattle_tracker_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paddock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('boundary', models.JSONField(blank=True, null=True)),
                ('acres', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('owner', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pasture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paddocks', to='cattle_tracker_app.pasture')),
            ],
        ),
    ]
