# Generated by Django 5.1.7 on 2025-05-12 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cattle_tracker_app', '0002_paddock'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pasture',
            table='cattle_tracker_app_pasture',
        ),
    ]
