# Generated by Django 5.1.7 on 2025-05-14 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cattle_tracker_app', '0003_alter_pasture_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='paddock',
            name='water_source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
