# Generated by Django 5.1.7 on 2025-05-17 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cattle_tracker_app', '0004_paddock_water_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paddock',
            name='water_source',
            field=models.CharField(blank=True, choices=[('pond', 'Pond'), ('creek', 'Creek'), ('trough', 'Trough'), ('well', 'Well'), ('none', 'None')], default='none', max_length=20, null=True),
        ),
    ]
