# Generated by Django 5.1.7 on 2025-05-20 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cattle_tracker_app', '0005_alter_paddock_water_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='cattle',
            name='is_leased',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cattle',
            name='leased_bull',
            field=models.ForeignKey(blank=True, limit_choices_to={'animal_type': 'bull', 'is_leased': True, 'sex': 'male', 'status': 'alive'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leased_offspring', to='cattle_tracker_app.cattle'),
        ),
    ]
