# Generated by Django 5.1.7 on 2025-05-20 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cattle_tracker_app', '0006_cattle_is_leased_cattle_leased_bull'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cattle',
            name='leased_bull',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cattle_bred_by_leased_bull', to='cattle_tracker_app.leasedbull'),
        ),
    ]
