# Generated by Django 5.1.7 on 2025-05-20 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cattle_tracker_app', '0009_cattle_leased_bull'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cattle',
            name='leased_bull',
        ),
    ]
