# Generated by Django 5.1.7 on 2025-05-20 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cattle_tracker_app', '0013_remove_cattle_test_leased_bull_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cattle',
            name='leased_bull',
        ),
        migrations.AddField(
            model_name='cattle',
            name='test_leased_bull',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cattle_tracker_app.leasedbull'),
        ),
    ]
