# Generated by Django 5.1.7 on 2025-05-21 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cattle_tracker_app', '0018_remove_cattle_leased_bull_clean_cattle_leased_bull'),
    ]

    operations = [
        migrations.AddField(
            model_name='cattle',
            name='paddock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cattle', to='cattle_tracker_app.paddock'),
        ),
    ]
