# Generated by Django 5.1.7 on 2025-05-23 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cattle_tracker_app', '0019_cattle_paddock'),
    ]

    operations = [
        migrations.AddField(
            model_name="healthrecord",
            name="status",
            field=models.CharField(max_length=20, default="active"),
            preserve_default=False,  # populate existing rows, but no model default afterward
        ),
    ]
