# Generated by Django 5.1.7 on 2025-05-25 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cattle_tracker_app', '0020_healthrecord_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paddock',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cattle_tracker_app.owner'),
        ),
        migrations.AlterField(
            model_name='pasture',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cattle_tracker_app.owner'),
        ),
    ]
