# Generated by Django 5.1.7 on 2025-05-26 18:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cattle_tracker_app', '0022_alter_pasture_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='cattle',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cattle',
            name='date_removed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paddock',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pastures', to='cattle_tracker_app.owner'),
        ),
        migrations.AlterField(
            model_name='pasture',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cattle_tracker_app.owner'),
        ),
    ]
