# Generated by Django 5.1.7 on 2025-05-29 21:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cattle_tracker_app', '0023_cattle_date_added_cattle_date_removed_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='user',
        ),
        migrations.AddField(
            model_name='owner',
            name='account_holder',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='owneruseraccess',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_records', to='cattle_tracker_app.owner'),
        ),
        migrations.AlterField(
            model_name='owneruseraccess',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_access_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='owneruseraccess',
            unique_together={('user', 'owner')},
        ),
    ]
