# Generated by Django 5.1.7 on 2025-05-30 01:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cattle_tracker_app', '0024_remove_owner_user_owner_account_holder_and_more'),
    ]

    operations = [
        
    ]
