# Generated by Django 5.1.7 on 2025-05-30 01:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cattle_tracker_app', '0025_pasture_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weightlog',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='weightlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
