# Generated by Django 5.1.7 on 2025-06-10 04:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cattle_tracker_app', '0026_alter_weightlog_options_weightlog_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='account_holder',
            new_name='user',
        ),
        migrations.AddField(
            model_name='pasture',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
