# Generated by Django 5.1.7 on 2025-06-10 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cattle_tracker_app', '0027_rename_account_holder_owner_user_pasture_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='user',
            new_name='account_holder',
        ),
    ]
