# Generated by Django 5.1.7 on 2025-06-10 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cattle_tracker_app', '0028_rename_user_owner_account_holder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='account_holder',
            new_name='User',
        ),
    ]
