# Generated by Django 5.1.7 on 2025-06-11 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cattle_tracker_app', '0029_rename_account_holder_owner_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turnoutgroup',
            name='owners',
            field=models.ManyToManyField(help_text='Owner involved in this group (optional)', to='cattle_tracker_app.owner'),
        ),
    ]
