# Generated by Django 5.1.7 on 2025-06-11 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cattle_tracker_app', '0030_alter_turnoutgroup_owners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turnoutgroup',
            name='owners',
            field=models.ManyToManyField(help_text='Owner involved with this group (optional)', to='cattle_tracker_app.owner'),
        ),
    ]
