# Generated by Django 5.1.7 on 2025-07-14 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cattle_tracker_app', '0033_leasedbull_breed_reg_num_leasedbull_breed_reg_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='herdsire',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='herd_sires/'),
        ),
    ]
