# Generated by Django 5.1.7 on 2025-07-14 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cattle_tracker_app', '0034_herdsire_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cattle',
            old_name='photo',
            new_name='image',
        ),
    ]
