# Generated by Django 5.1.7 on 2025-09-02 15:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cattle_tracker_app', '0035_rename_photo_cattle_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CastrationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(blank=True, choices=[('banding', 'Banding/Elastrator'), ('surgical', 'Surgical'), ('burdizzo', 'Burdizzo/Emasculatome'), ('other', 'Other')], max_length=20)),
                ('age_days', models.PositiveIntegerField(blank=True, null=True)),
                ('complications', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='illnessrecord',
            name='cattle',
        ),
        migrations.AlterModelOptions(
            name='healthrecord',
            options={'ordering': ['-date', '-id']},
        ),
        migrations.RemoveField(
            model_name='healthrecord',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='healthrecord',
            name='record_date',
        ),
        migrations.RemoveField(
            model_name='healthrecord',
            name='status',
        ),
        migrations.RemoveField(
            model_name='healthrecord',
            name='temperature',
        ),
        migrations.RemoveField(
            model_name='healthrecord',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='vaccinationrecord',
            name='cattle',
        ),
        migrations.RemoveField(
            model_name='vaccinationrecord',
            name='date_given',
        ),
        migrations.RemoveField(
            model_name='vaccinationrecord',
            name='next_due',
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='health_records/'),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='event_type',
            field=models.CharField(blank=True, choices=[('vaccination', 'Vaccination'), ('castration', 'Castration'), ('treatment', 'Treatment'), ('illness', 'Illness'), ('injury', 'Injury'), ('deworming', 'Deworming'), ('hoof_trim', 'Hoof Trim'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='next_due',
            field=models.DateField(blank=True, default=django.utils.timezone.now, help_text='For boosters, follow-ups, deworming schedules, etc.'),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='title',
            field=models.CharField(blank=True, help_text='Short label (optional)', max_length=120),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='vaccinationrecord',
            name='administration_method',
            field=models.CharField(blank=True, help_text='e.g., SubQ, IM, intranasal', max_length=50),
        ),
        migrations.AddField(
            model_name='vaccinationrecord',
            name='batch_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='vaccinationrecord',
            name='dose',
            field=models.CharField(blank=True, help_text='e.g., 5 mL', max_length=50),
        ),
        migrations.AddField(
            model_name='vaccinationrecord',
            name='health_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='cattle_tracker_app.healthrecord'),
        ),
        migrations.AddField(
            model_name='vaccinationrecord',
            name='withdrawal_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='healthrecord',
            index=models.Index(fields=['event_type', 'date'], name='cattle_trac_event_t_a19c9d_idx'),
        ),
        migrations.AddIndex(
            model_name='healthrecord',
            index=models.Index(fields=['next_due'], name='cattle_trac_next_du_4fb210_idx'),
        ),
        migrations.AddField(
            model_name='castrationrecord',
            name='health_record',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='castration_detail', to='cattle_tracker_app.healthrecord'),
        ),
        migrations.DeleteModel(
            name='IllnessRecord',
        ),
    ]
