# Generated by Django 5.1.7 on 2025-09-12 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cattle_tracker_app', '0036_castrationrecord_remove_illnessrecord_cattle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HerdBull',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fertility_test_date', models.DateField(blank=True, null=True)),
                ('fertility_status', models.CharField(blank=True, help_text='e.g., Satisfactory, Questionable', max_length=50, null=True)),
                ('scrotal_circumference_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('frame_score', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('semen_collected', models.BooleanField(default=False)),
                ('semen_straws_on_hand', models.PositiveIntegerField(default=0)),
                ('semen_storage_location', models.CharField(blank=True, max_length=120, null=True)),
                ('epd_profile_url', models.URLField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('cattle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='herd_bull_profile', to='cattle_tracker_app.cattle')),
            ],
            options={
                'verbose_name': 'Herd Bull',
                'verbose_name_plural': 'Herd Bulls',
            },
        ),
    ]
