# Generated by Django 5.1.7 on 2025-09-17 18:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cattle_tracker_app', '0037_herdbull'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pasture',
            options={'ordering': ('name',)},
        ),
        migrations.AlterField(
            model_name='pasture',
            name='avg_paddock_size_acres',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='pasture',
            name='size_acres',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='pasture',
            name='total_size_acres',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('location_description', models.CharField(blank=True, max_length=255)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cattle_tracker_app.owner')),
            ],
            options={
                'db_table': 'cattle_tracker_app_property',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='pasture',
            name='land_property',
            field=models.ForeignKey(blank=True, db_column='property_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pastures', to='cattle_tracker_app.property'),
        ),
        migrations.AlterUniqueTogether(
            name='pasture',
            unique_together={('land_property', 'name')},
        ),
    ]
