# Generated by Django 5.1.7 on 2025-09-17 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cattle_tracker_app', '0038_alter_pasture_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cattle',
            name='paddock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cattle_here', to='cattle_tracker_app.paddock'),
        ),
    ]
