# Generated by Django 5.1.7 on 2025-09-23 15:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cattle_tracker_app', '0039_alter_cattle_paddock'),
    ]

    operations = [
        migrations.AddField(
            model_name='paddock',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='cattle',
            name='date_added',
            field=models.DateField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
