# Generated by Django 5.1.7 on 2025-09-23 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cattle_tracker_app', '0040_paddock_is_active_alter_cattle_date_added'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Project To-Do',
                'verbose_name_plural': 'Project To-Do',
                'managed': True,
            },
        ),
    ]
