# Generated by Django 5.1.7 on 2025-10-06 17:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cattle_tracker_app', '0042_paddock_geometry_alter_pasture_geometry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paddock',
            options={'ordering': ('name', 'id')},
        ),
        migrations.RemoveField(
            model_name='paddock',
            name='owner',
        ),
        migrations.AlterField(
            model_name='paddock',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='paddock',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='paddock',
            name='pasture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paddocks', to='cattle_tracker_app.pasture'),
        ),
        migrations.AlterField(
            model_name='paddock',
            name='water_source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='paddock',
            index=models.Index(fields=['is_active'], name='cattle_trac_is_acti_f9d50a_idx'),
        ),
        migrations.AddIndex(
            model_name='paddock',
            index=models.Index(fields=['name'], name='cattle_trac_name_726d6a_idx'),
        ),
    ]
