# Generated by Django 5.1.7 on 2025-10-28 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cattle_tracker_app', '0043_alter_paddock_options_remove_paddock_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ranchsetting',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='ranchsetting',
            name='mailing_address',
            field=models.TextField(blank=True, help_text='Mailing address for correspondence and reports.', null=True),
        ),
        migrations.AddField(
            model_name='ranchsetting',
            name='name',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ranchsetting',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
