# Generated by Django 5.1.7 on 2025-11-10 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cattle_tracker_app', '0044_ranchsetting_email_ranchsetting_mailing_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthrecord',
            name='event_type',
            field=models.CharField(blank=True, choices=[('vaccination', 'Vaccination'), ('pregcheck', 'Pregcheck'), ('castration', 'Castration'), ('treatment', 'Treatment'), ('illness', 'Illness'), ('injury', 'Injury'), ('deworming', 'Deworming'), ('hoof_trim', 'Hoof Trim'), ('other', 'Other')], max_length=20, null=True),
        ),
    ]
