# Generated by Django 5.1.7 on 2025-12-11 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cattle_tracker_app', '0045_alter_healthrecord_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasture',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
