# Generated by Django 5.1.7 on 2025-12-11 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cattle_tracker_app', '0046_pasture_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pasture',
            name='notes',
        ),
    ]
