# Generated by Django 5.1.7 on 2026-02-23 04:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cattle_tracker_app', '0047_remove_pasture_notes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alert',
            name='dismissed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alert',
            name='snoozed_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cattle',
            name='status',
            field=models.CharField(choices=[('alive', 'Alive'), ('sold', 'Sold'), ('deceased', 'Deceased'), ('missing', 'Missing'), ('stolen', 'Stolen')], default='alive', max_length=10),
        ),
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('pregnancy_check', 'Pregnancy Confirmation Reminder'), ('calving_reminder', 'Upcoming Calving Reminder'), ('missed_pregnancy', 'Missed Pregnancy Alert'), ('failed_pregnancy', 'Failed Pregnancy Alert')], max_length=50)),
                ('lead_days', models.PositiveIntegerField(default=7)),
                ('enabled', models.BooleanField(default=True)),
                ('in_app', models.BooleanField(default=True)),
                ('email', models.BooleanField(default=False)),
                ('sms', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cattle_tracker_app.owner')),
            ],
        ),
        migrations.CreateModel(
            name='UserAlertPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(max_length=50)),
                ('muted_until', models.DateTimeField(blank=True, null=True)),
                ('in_app_enabled', models.BooleanField(default=True)),
                ('email_enabled', models.BooleanField(default=False)),
                ('sms_enabled', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cattle_tracker_app.owner')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'owner', 'alert_type')},
            },
        ),
    ]
